# Generated by Django 2.2.11 on 2020-03-24 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fktest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testfk_fktest', to='home.CustomText')),
            ],
        ),
    ]
